name: Retrieve Kubernetes OpenAPI Spec

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: "Kubernetes version (e.g., v1.29.0)"
        required: true
        default: "v1.29.0"

jobs:
  retrieve-swagger:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Install kubeadm, kubelet, kubectl
    - name: Install Kubernetes tools
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubelet kubeadm kubectl
        sudo apt-mark hold kubelet kubeadm kubectl

    # Step 2: Initialize Kubernetes cluster
    - name: Initialize Kubernetes cluster
      run: |
        sudo kubeadm init --kubernetes-version=${{ github.event.inputs.k8s_version }} --pod-network-cidr=192.168.0.0/16
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    # Step 3: Install a pod network (Weave, Calico, etc.)
    - name: Install network plugin
      run: |
        kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

    # Step 4: Retrieve OpenAPI spec
    - name: Retrieve OpenAPI spec
      run: |
        kubectl get --raw /openapi/v2 > k8s-openapi-${{ github.event.inputs.k8s_version }}.json

    # Step 5: Upload OpenAPI spec as an artifact
    - name: Upload OpenAPI spec
      uses: actions/upload-artifact@v3
      with:
        name: k8s-openapi-spec
        path: k8s-openapi-${{ github.event.inputs.k8s_version }}.json
