name: Retrieve Kubernetes OpenAPI Spec using minikube

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-22.04

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Install Go
      - name: Install Go
        run: |
          wget https://golang.org/dl/go1.20.6.linux-amd64.tar.gz
          sudo tar -C /usr/local -xvzf go1.20.6.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "Go installed."

      # Step 3: Clone cri-dockerd repository
      - name: Clone cri-dockerd repository
        run: git clone https://github.com/Mirantis/cri-dockerd.git

      # Step 4: Build cri-dockerd from source
      - name: Build cri-dockerd
        run: |
          cd cri-dockerd
          mkdir bin
          go get && go build -o bin/cri-dockerd
          sudo mkdir -p /usr/local/bin
          sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
          echo "cri-dockerd built successfully."

      # Step 5: Set up systemd for cri-dockerd
      - name: Set up systemd for cri-dockerd
        run: |
          sudo cp -a cri-dockerd/packaging/systemd/* /etc/systemd/system
          sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
          sudo systemctl daemon-reload
          sudo systemctl enable cri-docker.service
          sudo systemctl enable --now cri-docker.socket
          echo "cri-dockerd systemd configuration set."

      # Step 6: Install Docker and containerd
      - name: Install Docker and containerd
        run: |
          # Remove any conflicting 'containerd' package
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y

          # Clean up residual packages and dependencies
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo apt-get update
          
          # Run docker
          sudo systemctl enable --now docker
          sudo gpasswd -a $USER docker
          echo "Docker and containerd installed and started."

      # Step 7: Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --kubernetes-version=v1.29.0 --driver=none --container-runtime=docker
          echo "Minikube started successfully."

      # Step 8: Retrieve Kubernetes Swagger JSON (OpenAPI spec)
      - name: Retrieve Kubernetes Swagger JSON
        run: |
          kubectl get --raw /openapi/v2 > k8s-openapi-v1.29.0.json
          echo "Swagger JSON retrieved successfully."

      # Step 9: Upload Swagger JSON as an artifact
      - name: Upload Swagger JSON Artifact
        uses: actions/upload-artifact@v3
        with:
          name: k8s-openapi-v1.29.0.json
          path: k8s-openapi-v1.29.0.json
