name: Retrieve Kubernetes OpenAPI Spec using minikube

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: "Kubernetes version (e.g., v1.29.0)"
        required: true
        default: "v1.29.0"

jobs:
  retrieve-swagger:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Install conntrack
    - name: Install conntrack
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack

    # Step 2: Install crictl
    - name: Install crictl
      run: |
        CRICTL_VERSION="v1.29.0"
        wget https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-$(uname -s)-$(uname -m).tar.gz
        tar -zxvf crictl-$(uname -s)-$(uname -m).tar.gz
        sudo mv crictl /usr/local/bin/
        rm -rf crictl-$(uname -s)-$(uname -m).tar.gz

    # Step 3: Install Minikube and kubectl
    - name: Install Minikube and kubectl
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        curl -LO "https://dl.k8s.io/release/${{ github.event.inputs.k8s_version }}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # Step 4: Start Minikube
    - name: Start Minikube
      run: |
        sudo minikube start --kubernetes-version=${{ github.event.inputs.k8s_version }} --driver=none

    # Step 5: Retrieve OpenAPI spec
    - name: Retrieve OpenAPI spec
      run: |
        kubectl get --raw /openapi/v2 > k8s-openapi-${{ github.event.inputs.k8s_version }}.json

    # Step 6: Upload OpenAPI spec as an artifact
    - name: Upload OpenAPI spec
      uses: actions/upload-artifact@v3
      with:
        name: k8s-openapi-spec
        path: k8s-openapi-${{ github.event.inputs.k8s_version }}.json
