name: Retrieve Kubernetes OpenAPI Spec

on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: "Kubernetes version to retrieve the OpenAPI spec for"
        required: true
        default: "v1.28.0"

jobs:
  retrieve-openapi:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Start etcd
      - name: Start etcd
        run: |
          docker run -d --name etcd --network=host -e ALLOW_NONE_AUTHENTICATION=yes quay.io/coreos/etcd:v3.5

      # Step 3: Run kube-apiserver for the specified version
      - name: Start kube-apiserver
        run: |
          docker run -d --name kube-apiserver --network=host \
            k8s.gcr.io/kube-apiserver:${{ github.event.inputs.k8s_version }} \
            --etcd-servers=http://127.0.0.1:2379 \
            --authorization-mode=Node,RBAC \
            --service-account-issuer=https://kubernetes.default.svc.cluster.local \
            --service-account-signing-key-file=/tmp/service-account.key \
            --service-account-key-file=/tmp/service-account.pem \
            --advertise-address=127.0.0.1

      # Step 4: Wait for kube-apiserver to be ready
      - name: Wait for kube-apiserver
        run: |
          for i in {1..30}; do
            curl -s http://127.0.0.1:6443/healthz && break || sleep 2;
          done

      # Step 5: Retrieve the OpenAPI spec
      - name: Retrieve OpenAPI Spec
        run: |
          curl -s http://127.0.0.1:6443/openapi/v2 > k8s-openapi-${{ github.event.inputs.k8s_version }}.json

      # Step 6: Save the OpenAPI spec
      - name: Save OpenAPI Spec
        run: |
          mkdir -p kubernetes-specs
          mv k8s-openapi-${{ github.event.inputs.k8s_version }}.json kubernetes-specs/

      # Step 7: Commit and push the file (if applicable)
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add OpenAPI spec for Kubernetes ${{ github.event.inputs.k8s_version }}"
          branch: main
