name: Update Kubernetes Versions in Matrix

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update-kubernetes-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest Kubernetes versions
        id: fetch_versions
        run: |
          versions=$(curl -s https://api.github.com/repos/kubernetes/kubernetes/releases \
                      | jq -r '.[] | select(.prerelease == false and .draft == false) | .tag_name' \
                      | grep '^v[0-9]\+\.[0-9]\+' | head -3)
                    echo "versions=$versions" >> $GITHUB_ENV

      - name: Update matrix in workflow file
        run: |
          workflow_file=".github/workflows/minikube.yml"
          updated_versions=$(echo "[${{ env.versions }}" | sed 's/ /", "/g')
          sed -i 's/\(kubernetes-version:\s*\)\[.*\]/\1'"$updated_versions"'/' $workflow_file

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/minikube.yml
          git commit -m "Update Kubernetes versions in matrix strategy"
          git push

      - name: Trigger downstream workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/minikube.yml/dispatches \
            -d '{"ref":"main"}'
