name: Update Kubernetes Versions in Matrix

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  update-kubernetes-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history for branch creation

      - name: Fetch latest Kubernetes versions
        id: fetch_versions
        run: |
          versions=$(curl -s https://api.github.com/repos/kubernetes/kubernetes/releases \
                | jq -r '.[] | select(.prerelease == false and .draft == false) | .tag_name' \
                | grep '^v[0-9]\+\.[0-9]\+' | head -3 | xargs)
          echo "versions=$(echo $versions | sed 's/ /,/g')" >> $GITHUB_ENV

      - name: Update matrix in workflow file
        run: |
          workflow_file=".github/workflows/minikube.yml"
          updated_versions=$(echo "[${{ env.versions }}]" | sed 's/,/\", \"/g')
          sed -i '' 's/\(kubernetes-version:\s*\)\[.*\]/\1'"$updated_versions"'/' $workflow_file

      - name: Sync .github/workflows files from main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="update-workflows-$(date +'%Y%m%d%H%M%S')"
          COMMIT_SHA=$(git rev-parse origin/main)
          ROOT_DIR=$(pwd)

          git checkout origin/main # Ensure we're on the main branch
          git switch -c $BRANCH_NAME
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $ROOT_DIR/.github/workflows
          git commit -m "chore: sync .github/workflows files from main branch" || true # Skip if nothing to commit

      - name: Create Pull Request for Workflow Sync
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          title: "Sync Workflows"
          body: |
            This PR syncs the `.github/workflows` folder with the default branch (main)
            to ensure consistency and avoid conflicts.

      - name: Commit and push Kubernetes version changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/workflows/minikube.yml
          git commit -m "Update Kubernetes versions matrix: ${{ env.versions }}"
          git push origin main

      - name: Trigger downstream workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/minikube.yml/dispatches \
            -d '{"ref":"main"}'
